### ISSUE TITLE
Settings.apk

### ISSUE THREAD

**Issue by Marcosuper7** [DqrKnzx/HyperOS-XML-1.0-SPANISH#2]
Muy buenas, os dejo este reporté para corregir del inglés al español, gracias 

 ![IMG_20240817_203853_382](https://github.com/user-attachments/assets/2152eb6e-c4b7-4523-abd2-19b9e8c1fd31)
![IMG_20240817_203852_951](https://github.com/user-attachments/assets/2b9dd51f-4a79-4427-8851-2b4027ef6657)

**Comment by deivids84** [comment]
![IMG_20240817_203853_382](https://github.com/user-attachments/assets/2152eb6e-c4b7-4523-abd2-19b9e8c1fd31)
![IMG_20240817_203852_951](https://github.com/user-attachments/assets/2b9dd51f-4a79-4427-8851-2b4027ef6657)

**Comment by Marcosuper7** [comment]
> Muy buenas, os dejo este reporté para corregir del inglés al español, gracias

**Comment by Marcosuper7** [comment]
Completado 👍🏼👌🏼

**Comment by Marcosuper7** [comment]
Completado👍🏼👌🏼
![Screenshot_2024-08-22-23-57-25-459_com android settings-edit](https://github.com/user-attachments/assets/c94ed741-246e-4f7d-9725-bc20e5645da6)
![Screenshot_2024-08-22-23-56-40-510_com android settings-edit](https://github.com/user-attachments/assets/bee986ec-3f31-4d55-bf33-f14421b545a5)
